runtime: nodejs16
handlers:
- url: /style/
  static_dir: static/style
- url: /js/
  static_dir: static/js
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
- url: /.+
  script: main.app
- url: /
  static_files: static/index.html
  upload: static/index.html
